### ISSUE TITLE
Error when installing Kibana 7.11.2

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#3721]
Hello team!

The aim of this issue is to fix the installation of Kibana 7.11.2 since it has introduced some changes in the configuration that break the installation.

This is the output given:

`kibana[8295]: (node:8295) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verifica
kibana[8295]: (Use node --trace-warnings ... to show where the warning was created)
kibana[8295]: Node.js process-warning detected:
kibana[8295]: Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
kibana[8295]: at getAllowUnauthorized (internal/options.js:21:13)
kibana[8295]: at Object.connect (_tls_wrap.js:1560:29)
kibana[8295]: at Agent.createConnection (https.js:129:22)
kibana[8295]: at Agent.createSocket (_http_agent.js:323:26)
kibana[8295]: at Agent.addRequest (_http_agent.js:274:10)
kibana[8295]: at new ClientRequest (_http_client.js:306:16)
systemd[1]: kibana.service: main process exited, code=exited, status=1/FAILURE
systemd[1]: Unit kibana.service entered failed state.
systemd[1]: kibana.service failed.
systemd[1]: kibana.service holdoff time over, scheduling restart.
systemd[1]: Stopped Kibana.
systemd[1]: Started Kibana.
kibana[8341]: (node:8341) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verifica
kibana[8341]: (Use node --trace-warnings ... to show where the warning was created)
kibana[8341]: Node.js process-warning detected:
kibana[8341]: Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
kibana[8341]: at getAllowUnauthorized (internal/options.js:21:13)
systemd[1]: kibana.service: main process exited, code=exited, status=1/FAILURE
systemd[1]: Unit kibana.service entered failed state.
systemd[1]: kibana.service failed.
`

We must update the configuration file and adapt it to the incoming changes.

Regards,

David

**Comment by davidfmiranda** [comment]
We have adapted the Kibana templates to use DNS instead of IPs.

Regards,

David
