### ISSUE TITLE
Improve Puppet installation documentation

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-documentation#5126]
# Description

There are some errors that occur if we try to follow the Puppet installation instructions as they appear in our documentation. I only tried Ubuntu 20.04.

In fact, I found this guide at PhoenixNAP to be more accurate and easier to follow than our own, despite being short and basic:
- [How to Install Puppet on Ubuntu 20.04](https://phoenixnap.com/kb/install-puppet-ubuntu)  (it uses Puppet6 but it works too if Puppet7 is used instead)

## 1. Add info about `/etc/hosts` (suggestion)
We are mentioning this in the [Setup Puppet page](https://github.com/wazuh/wazuh-documentation/blob/4.3-rc/source/deployment-options/deploying-with-puppet/setup-puppet/index.rst) of our documentation:

> If you do not have DNS configured, you must use your hosts file for name resolution. We will assume that you will use your private network for communication within your infrastructure.

In addition, later sections show configurations containing an example domain that should have been configured in the `hosts` file:
![image](https://user-images.githubusercontent.com/23361101/165516323-f1241912-b5dd-4206-8abe-3b19b78ef079.png)

This means that we are assuming that the user will install Puppet in a local environment, but the steps that we offer in the installation do not include everything necessary for the correct operation in a local setup, leading to errors and misunderstandings. 

Therefore, I think that a small section or an additional step at the beginning could be very useful, indicating that both the Puppet master and agent hosts will need this in their `/etc/hosts` file (or the equivalent in other OS) in local environments:
```
[puppet master ip] puppet puppet.example.com
[puppet agent ip] puppetagent
```

## 2. Puppet agent configuration
This is a little error. The [Configuration section](https://github.com/wazuh/wazuh-documentation/blob/4.3-rc/source/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-agent.rst#configuration) of the Puppet agent page is nested within `Windows installation`. It should not be nested since it is required for any OS.

Also, I think we should add the `certname` to the `puppet.conf` file, which should match the content of the `/etc/hosts` file:
```
[main]
certname = puppetagent
server = puppet
```

And finally, starting, enabling (this is already done in our documentation), and maybe checking the status of the Puppet service should be added:
```
sudo systemctl start puppet
sudo systemctl enable puppet
```
```
sudo systemctl status puppet
```

 
## 3. Setting up Puppet certificates
The command to list certificates (`puppetserver ca list`) on the Puppet master, as it appears right now in the documentation, raises the following exception:
```
Traceback (most recent call last):
	9: from /opt/puppetlabs/server/apps/puppetserver/cli/apps/ca:5:in `<main>'
	8: from /opt/puppetlabs/puppet/lib/ruby/vendor_gems/gems/puppetserver-ca-2.3.6/lib/puppetserver/ca/cli.rb:100:in `run'
	7: from /opt/puppetlabs/puppet/lib/ruby/vendor_gems/gems/puppetserver-ca-2.3.6/lib/puppetserver/ca/action/list.rb:103:in `run'
	6: from /opt/puppetlabs/puppet/lib/ruby/vendor_gems/gems/puppetserver-ca-2.3.6/lib/puppetserver/ca/action/list.rb:226:in `get_certs_or_csrs'
	5: from /opt/puppetlabs/puppet/lib/ruby/vendor_gems/gems/puppetserver-ca-2.3.6/lib/puppetserver/ca/action/list.rb:226:in `new'
	4: from /opt/puppetlabs/puppet/lib/ruby/vendor_gems/gems/puppetserver-ca-2.3.6/lib/puppetserver/ca/certificate_authority.rb:26:in `initialize'
	3: from /opt/puppetlabs/puppet/lib/ruby/vendor_gems/gems/puppetserver-ca-2.3.6/lib/puppetserver/ca/certificate_authority.rb:26:in `new'
	2: from /opt/puppetlabs/puppet/lib/ruby/vendor_gems/gems/puppetserver-ca-2.3.6/lib/puppetserver/ca/utils/http_client.rb:25:in `initialize'
	1: from /opt/puppetlabs/puppet/lib/ruby/vendor_gems/gems/puppetserver-ca-2.3.6/lib/puppetserver/ca/utils/http_client.rb:156:in `make_store'
/opt/puppetlabs/puppet/lib/ruby/vendor_gems/gems/puppetserver-ca-2.3.6/lib/puppetserver/ca/utils/http_client.rb:156:in `add_file': system lib (OpenSSL::X509::StoreError)
```

I tried using `puppetserver ca setup` and that fixed it, but it led to other errors in later steps. Finally, at least in my tests, I found out that the correct way to work with the `puppetserver ca` commands is to use it with `sudo`:
```
sudo /opt/puppetlabs/bin/puppetserver ca list
```

We should update our documentation to use it this way. The same should be done for signing certs:
![image](https://user-images.githubusercontent.com/23361101/165519852-6e20e283-b89e-4414-8480-dd10a2d390e6.png)

`sudo` is required and maybe using the same example as in the previous sections would make it easier to understand:
```
sudo /opt/puppetlabs/bin/puppetserver ca sign --certname puppetagent
```
or
```
sudo /opt/puppetlabs/bin/puppetserver ca sign --all
```

**Comment by Spades0** [comment]
1. Section to edit the `/etc/hosts` files has been included.
2. a. The Configuration section indent has been corrected.
    b. This command `puppetserver ca sign --certname pending-agent-node` is sufficient to sign certificates.
    c.  `sudo systemctl status puppet` has been added.
3. This symlink has been added: `ln -s /opt/puppetlabs/server/bin/puppetserver /bin` to fix the issue of using full part. The text has also been rephrased.
