### ISSUE TITLE
Typos in Splunk integration configuration and commands

### ISSUE THREAD

**Issue by javimed** [wazuh/wazuh-documentation#6556]
In the [Splunk integration guide](https://documentation-dev.wazuh.com/v4.6.0-beta1/integrations-guide/splunk/index.html) the following typos have been found:

#### Missing quotation marks in `cacert => "</PATH/TO/LOCAL/SPLUNK/CERTIFICATE>/ca.pem"` placeholder

![imagen](https://github.com/wazuh/wazuh-documentation/assets/47069802/38b81598-972f-4566-ab2e-23963e073f3b)

```
[ec2-user@ip-172-31-37-247 bin]$ cat /etc/logstash/conf.d/wazuh-splunk.conf
input {
  opensearch {
   hosts =>  ["....:9200"]
   user  =>  "${WAZUH_INDEXER_USERNAME}"
   password  =>  "${WAZUH_INDEXER_PASSWORD}"
   index =>  "wazuh-alerts-4.x-*"
   ssl => true
   ca_file => "/etc/logstash/wazuh-indexer-certs/root-ca.pem"
   query =>  '{
       "query": {
          "range": {
             "@timestamp": {
                "gt": "now-1m"
             }
          }
       }
   }'
   schedule => "* * * * *"
  }
}
output {
   http {
      format => "json" # format of forwarded logs
      http_method => "post" # HTTP method used to forward logs
      url => "....:8088/services/collector/raw" # endpoint to forward logs to
      headers => ["Authorization", "Splunk ${SPLUNK_AUTH}"]
      cacert => /etc/logstash/splunk-certs/ca.pem
   }
}
[ec2-user@ip-172-31-37-247 bin]$ 
```

```
[ec2-user@ip-172-31-37-247 bin]$ sudo -E /usr/share/logstash/bin/logstash -f /etc/logstash/conf.d/wazuh-splunk.conf --path.settings /etc/logstash/
Using bundled JDK: /usr/share/logstash/jdk
Sending Logstash logs to /var/log/logstash which is now configured via log4j2.properties
[2023-09-25T19:20:06,167][INFO ][logstash.runner          ] Log4j configuration path used is: /etc/logstash/log4j2.properties
[2023-09-25T19:20:06,170][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"8.10.2", "jruby.version"=>"jruby 9.4.2.0 (3.1.0) 2023-03-08 90d2913fda OpenJDK 64-Bit Server VM 17.0.8+7 on 17.0.8+7 +indy +jit [x86_64-linux]"}
[2023-09-25T19:20:06,174][INFO ][logstash.runner          ] JVM bootstrap flags: [-Xms1g, -Xmx1g, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djruby.compile.invokedynamic=true, -XX:+HeapDumpOnOutOfMemoryError, -Djava.security.egd=file:/dev/urandom, -Dlog4j2.isThreadContextMapInheritable=true, -Djruby.regexp.interruptible=true, -Djdk.io.File.enableADS=true, --add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED, --add-opens=java.base/java.security=ALL-UNNAMED, --add-opens=java.base/java.io=ALL-UNNAMED, --add-opens=java.base/java.nio.channels=ALL-UNNAMED, --add-opens=java.base/sun.nio.ch=ALL-UNNAMED, --add-opens=java.management/sun.management=ALL-UNNAMED]
[2023-09-25T19:20:06,603][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2023-09-25T19:20:07,648][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600, :ssl_enabled=>false}
[2023-09-25T19:20:08,243][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of [ \\t\\r\\n], \"#\", [A-Za-z0-9_-], '\"', \"'\", [A-Za-z_], \"-\", [0-9], \"[\", \"{\" at line 27, column 17 (byte 741) after output {\n   http {\n      format => \"json\" # format of forwarded logs\n      http_method => \"post\" # HTTP method used to forward logs\n      url => \"23....:8088/services/collector/raw\" # endpoint to forward logs to\n      headers => [\"Authorization\", \"Splunk ${SPLUNK_AUTH}\"]\n      cacert => ", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:32:in `compile_imperative'", "org/logstash/execution/AbstractPipelineExt.java:239:in `initialize'", "org/logstash/execution/AbstractPipelineExt.java:173:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:48:in `initialize'", "org/jruby/RubyClass.java:931:in `new'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:49:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:386:in `block in converge_state'"]}
[2023-09-25T19:20:08,268][INFO ][logstash.runner          ] Logstash shut down.
[2023-09-25T19:20:08,274][FATAL][org.logstash.Logstash    ] Logstash stopped processing because of an error: (SystemExit) exit
org.jruby.exceptions.SystemExit: (SystemExit) exit
	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:795) ~[jruby.jar:?]
	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:758) ~[jruby.jar:?]
	at usr.share.logstash.lib.bootstrap.environment.<main>(/usr/share/logstash/lib/bootstrap/environment.rb:90) ~[?:?]
[ec2-user@ip-172-31-37-247 bin]$ 
```

#### Extra parameter not required when saving keystore password

![imagen](https://github.com/wazuh/wazuh-documentation/assets/47069802/6d115d25-8d8e-4f61-a675-bf68fa036d73)

```
[ec2-user@ip-172-31-37-38 ~]$ echo 'LOGSTASH_KEYSTORE_PASS="123456"'| sudo tee /etc/sysconfig/logstash
LOGSTASH_KEYSTORE_PASS="123456"
[ec2-user@ip-172-31-37-38 ~]$ sudo cat /etc/sysconfig/logstash
LOGSTASH_KEYSTORE_PASS="123456"
[ec2-user@ip-172-31-37-38 ~]$ 
```

```
[ec2-user@ip-172-31-37-38 ~]$ export LOGSTASH_KEYSTORE_PASS="123456"
[ec2-user@ip-172-31-37-38 ~]$ echo $LOGSTASH_KEYSTORE_PASS
123456
[ec2-user@ip-172-31-37-38 ~]$ 
```

**Comment by TheMuntu** [comment]
Hello @javimed, they have all been reviewed and updated. Thank you very much for your feedback.

**Comment by javimed** [comment]
Thanks @TheMuntu let me add that we're suggesting a dashboard which is unfinished and doesn't seem useful:

![imagen](https://github.com/wazuh/wazuh-documentation/assets/47069802/01d1ec96-905c-45e2-8607-e24130d21b61)

![imagen](https://github.com/wazuh/wazuh-documentation/assets/47069802/d6b1d088-230d-4c18-a54b-45ce7563c491)

**Comment by TheMuntu** [comment]
Thank you @javimed, I removed it from the list for the moment. I'll talk with @wazuh/frontend team to know more about its ETA.

**Comment by javimed** [comment]
And one last thing, on step 4

![imagen](https://github.com/wazuh/wazuh-documentation/assets/47069802/e81f8bc4-ffa1-4383-b08e-98861ee41d9d)

The title gets overwritten by the title set in the dashboard template we're importing. Maybe some tweak in wording would help to warn about this

**Comment by TheMuntu** [comment]
I added a note for this also. Thank you!!
