### ISSUE TITLE
Add K8s password change to documentation

### ISSUE THREAD

**Issue by 4rth4S** [wazuh/wazuh-documentation#6574]
Regarding to this issue 
- https://github.com/wazuh/wazuh/issues/19159

It was detected the `k8s password change` is missing in the official docs of wazuh. It is possible to achieve the goal by following the following steps:

It will be awesome to have it. 

--------------------------------------------------------------------------------------------

## Steps to change the password

The procedure to change the password is:

1- Obtain hash password in the indexer pod:
  - outside pod:
    ```BASH
    kubectl exec -it -n wazuh pod/wazuh-indexer-0 -- bash
    ```
  - inside pod:
    ```BASH
    export JAVA_HOME=/usr/share/wazuh-indexer/jdk
    bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/hash.sh
    ```
    
2-  Insert the new password and create a new hash. Replace admin value with new hash into `wazuh/indexer_stack/wazuh-indexer/indexer_conf/internal_users.yml` file.
3- Change value of `password` parameter in the `wazuh/secrets/indexer-cred-secret.yaml` file. You need to encrypt the password with base64:
```BASH
echo -n <new_hash> | base64
```
4- Apply changes into your k8s cluster:
```BASH
kubectl apply -k envs/eks/
```
If this is your first start of the deployment, this is the end of the procedure, otherwise you must continue with the following tasks.

5- Add environment variables and run `securityadmin` script (from the `wazuh-indexer-0` pod):
```BASH
export INSTALLATION_DIR=/usr/share/wazuh-indexer
export OPENSEARCH_PATH_CONF=${INSTALLATION_DIR}/config
CACERT=$OPENSEARCH_PATH_CONF/certs/root-ca.pem
KEY=$OPENSEARCH_PATH_CONF/certs/admin-key.pem
CERT=$OPENSEARCH_PATH_CONF/certs/admin.pem
export JAVA_HOME=/usr/share/wazuh-indexer/jdk
bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh -cd /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/ -nhnv -cacert  $CACERT -cert $CERT -key $KEY -p 9300 -icl
```
6- Restart (delete) the Wazuh manager pods (master and workers).
7- Clear cache and test yout new password

**Comment by dptaf** [comment]
Hello, when doing this on a GKE cluster we're getting the following error:

Security Admin v7
Will connect to localhost:9300 ... done
ERR: An unexpected RuntimeException occured: error while performing request
Trace:
java.lang.RuntimeException: error while performing request
        at org.opensearch.client.RestClient.extractAndWrapCause(RestClient.java:963)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:332)
        at org.opensearch.client.RestClient.performRequest(RestClient.java:320)
        at org.opensearch.security.tools.SecurityAdmin.execute(SecurityAdmin.java:465)
        at org.opensearch.security.tools.SecurityAdmin.main(SecurityAdmin.java:162)
Caused by: org.apache.http.ProtocolException: Not a valid protocol version: This is not an HTTP port
        at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:209)
        at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:245)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:87)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:40)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:121)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.http.ParseException: Not a valid protocol version: This is not an HTTP port
        at org.apache.http.message.BasicLineParser.parseProtocolVersion(BasicLineParser.java:148)
        at org.apache.http.message.BasicLineParser.parseStatusLine(BasicLineParser.java:366)
        at org.apache.http.impl.nio.codecs.DefaultHttpResponseParser.createMessage(DefaultHttpResponseParser.java:112)
        at org.apache.http.impl.nio.codecs.DefaultHttpResponseParser.createMessage(DefaultHttpResponseParser.java:50)
        at org.apache.http.impl.nio.codecs.AbstractMessageParser.parseHeadLine(AbstractMessageParser.java:156)
        at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:207)
        ... 11 more
        
 Any ideas why?

**Comment by praetorianer777** [comment]
Same error as @dptaf on our on premise k8s cluster
